#!/bin/sh
HOST_TRIPLE=i386-unknown-linux
export COMMON=
export COMPILE="--with-ghc=${HOST_TRIPLE}-ghc
                --with-ghc-pkg=${HOST_TRIPLE}-ghc-pkg
                --with-gcc=${HOST_TRIPLE}-gcc
                --with-ld=${HOST_TRIPLE}-ld"
export CONFIG="--configure-option=--host=${HOST_TRIPLE} --disable-shared"
case $1 in
    configure|install) OPTIONS="$COMMON $COMPILE $CONFIG" ;;
    build)             OPTIONS="$COMMON $COMPILE" ;;
    list|info|update)  OPTIONS="" ;;
    "")                OPTIONS="" ;;
    *)                 OPTIONS="$COMMON" ;;
esac
exec cabal $OPTIONS "$@"
