#!/bin/sh
HOST_TRIPLE=i686-w64-mingw32
export COMMON=
export COMPILE="--with-ghc=${HOST_TRIPLE}-ghc
                --with-ghc-pkg=${HOST_TRIPLE}-ghc-pkg
                --with-gcc=${HOST_TRIPLE}-gcc
                --with-hsc2hs=/usr/src/mxe/usr/i386-unknown-linux/bin/hsc2hs
                --hsc2hs-options=--emulator=$(which wine)
                --hsc2hs-options=--template=/usr/src/mxe/usr/lib/${HOST_TRIPLE}-ghc-${GHC_VERSION}/template-hsc.h
                --with-ld=${HOST_TRIPLE}-ld"
export CONFIG="--configure-option=--host=${HOST_TRIPLE} --disable-shared"
case $1 in
    configure|install) OPTIONS="$COMMON $COMPILE $CONFIG" ;;
    build)             OPTIONS="$COMMON $COMPILE" ;;
    list|info|update)  OPTIONS="" ;;
    "")                OPTIONS="" ;;
    *)                 OPTIONS="$COMMON" ;;
esac
exec cabal $OPTIONS "$@"
